name: receipt
description: A new receipt package for print
version: 1.0.0-dev.2
repository: "https://github.com/yegobox/receipt"

environment:
  sdk: ">=3.3.4 <4.0.0"


dependencies:
  flutter:
    sdk: flutter
  printing: ^5.13.3
  pdf: ^3.10.3
  open_filex: ^4.7.0
  gap: ^2.0.0
  flipper_models: any

  qr_flutter: ^4.0.0
  flipper_services: any
  universal_platform: ^1.0.0+1
  path_provider: ^2.1.5
  path: ^1.8.1
  permission_handler: ^12.0.1
  image: ^4.1.0
  intl: ^0.20.2
  dotted_line: ^3.2.2
  talker_flutter: ^4.1.5
  syncfusion_flutter_pdf: ^29.2.11
  supabase_models: any
  flipper_rw: any
  jni: ^0.14.2
  example_receipt: any

dependency_overrides:
  http: ^1.2.2
  meta: ^1.16.0
  web: ^1.1.0
  sqlite3: ^3.3.1
  device_info_plus: ^12.3.0
  drift: ^2.29.0
  cbor: ^6.3.7
  jni: ^0.14.2
  

dev_dependencies:
  flutter_lints: ^5.0.0
  build_runner: ^2.0.0

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/logo_left.png
    - assets/flipper_logo.png
    - assets/logo_right.png
    - assets/fonts/NotoSans-Regular.ttf
